### ISSUE TITLE
Provide mechanism to restore dashboards to graphite server

### ISSUE THREAD

**Issue by virtuald** [sous-chefs/graphite#159]
It would be great to provide this functionality. I've written a [script](http://www.virtualroadside.com/blog/index.php/2014/04/24/downloading-and-uploading-dashboards-tofrom-a-graphite-server/) that loads/saves dashboards from graphite, I'd love to be able to specify a dashboard to load to my newly provisioned graphite server. 

This would be a great thing to add as an LWRP to the new graphite cookbook rework in https://github.com/hw-cookbooks/graphite/pull/147

**Comment by damacus** [comment]
This one has been open for 3 years now. I'm going to go ahead and close it down.
