### ISSUE TITLE
Missing graphite runit log template?

### ISSUE THREAD

**Issue by webframp** [sous-chefs/graphite#185]
Saw this reported in `#graphite` but didn't have a chance to ask user for details:

```
11:38 PM <bfraser> hmm, new cookbook doesn't seem to work either .. 
missing log template when using runit
```

I don't believe that's the case now, since we set `default_logger: true`: https://github.com/hw-cookbooks/graphite/blob/master/providers/service_runit.rb#L38

but we should confirm. Filing an issue so I don't forget.

**Comment by abilun** [comment]
I think tihs ticket should be closed since runit is no longer used in this project.
