### ISSUE TITLE
Unable to create standalone carbon relay

### ISSUE THREAD

**Issue by drywheat** [sous-chefs/graphite#199]
`carbon-relay.py` fails to execute after using the following recipe/LWRP:

``` ruby
include_recipe "graphite::carbon"

graphite_carbon_relay "i_stand_alone" do
  config(...) # them details
end
```

and here's the exception that is thrown:

![image](https://cloud.githubusercontent.com/assets/65274/4729156/5e37bb08-5980-11e4-9de2-f04dff778367.png)

I checked the system and confirmed that `pip` never installed "whisper" on the system.

The `graphite_carbon_cache` LWRP installs "whisper" using a **backend** attribute whereas `graphite_carbon_relay` is lacking this sub-operation.

I can understand the reasoning behind forgoing a backend install (i.e. whisper ) when creating a relay, but the fact remains that the carbon-relay daemon will not launch without it.

**Comment by damacus** [comment]
Closing this issue down as it looks like it's solved. 

Thanks all!
