### ISSUE TITLE
Unsure of how to add authentication to graphite

### ISSUE THREAD

**Issue by jeffmacdonald** [sous-chefs/graphite#215]
Hi,

I'd like to be able to add a user so that I can save graphs etc.  Unsure of which attribute to edit to make this happen.

Jeff.

**Comment by jeffmacdonald** [comment]
Nevermind. I found it. :) For future users. You can dig it out of the single node example, however take care to change it from using node['graphite']['user'] to perhaps something else as the presence of this attribute causes other behaviors which need to be debugged.

**Comment by damacus** [comment]
@jeffmacdonald thanks very much for letting us know. 

Closing this one down as it looks resolved (please ping me if it isn't!)
