### ISSUE TITLE
Not sure what should be run list for graphite_example cookbook

### ISSUE THREAD

**Issue by praste** [sous-chefs/graphite#216]
I am new to chef and trying to figure out how to make this cookbook work.
What run list should I use for it I want to try this cookbook out using graphite_example cookbook

**Comment by bdangit** [comment]
Agree.  There is a lot in here to digest in here and try to understand, especially if you are new.

For starters, you can try `single_node.rb` if you want everything in one box.

**Comment by damacus** [comment]
Closing this down. Please drop into the general or sous-chefs channel on chefcommunity.slack.com for more help!
