### ISSUE TITLE
Default django-tagging version incompatible with default Django version

### ISSUE THREAD

**Issue by jgoldschrafe** [sous-chefs/graphite#231]
The default version of django-tagging installed by this cookbook (currently 0.4) is incompatible with Django 1.5.5. Version 0.3.6, the last compatible version, should be installed instead.

**Comment by runningman84** [comment]
this seems to be a working fix:
https://github.com/channelgrabber/graphite/pull/1

**Comment by damacus** [comment]
Thanks for the report. 

This issue have been open for over 2 years and the cookbook has changed enough to warrant re-testing this bug. 

If you still have this issue please reopen!
