### ISSUE TITLE
Note failure on Ubuntu 12.04 with latest Chef versions

### ISSUE THREAD

**Issue by luckymike** [sous-chefs/graphite#250]
Ubuntu 12.04 & Chef Client > 12.6 will blow up on the python_pip resources. We should note this in the Readme to avert tears.

**Comment by yticketfly** [comment]
Is there a workaround this? I got `pip` failures, e.g.
`Error executing actioninstallon resource 'python_pip[uwsgi]'`

**Comment by yticketfly** [comment]
seems downgrading works
`curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -v 12.5.1`

**Comment by luckymike** [comment]
Yes, downgrading will work, since the failure occurs in 12.6+

**Comment by damacus** [comment]
We're going to stop supporting Ubuntu 12.04 since it's no EOL. 

The `python_pip` resource will be going away in the future too in favour of poise-python.
