### ISSUE TITLE
Default django version for `0.9.15` is too high

### ISSUE THREAD

**Issue by howdoicomputer** [sous-chefs/graphite#272]
The default attribute for the version of django used is `1.9.0`. However, the `0.9.15` version of Graphite only supports up to version `1.8.X` with the officially supported and locked version at `1.4`. If 1.9.0 is installed then graph rendering fails with a stack trace.

**Comment by tas50** [comment]
@howdoicomputer Where do you see the django pin to 1.4? https://graphite.readthedocs.io/en/latest/install.html has 1.9, which is what I was going off.

**Comment by howdoicomputer** [comment]
@tas50 https://github.com/graphite-project/graphite-web/issues/1519

Unless I'm missing something. Low on sleep so that's totally possible.

**Comment by howdoicomputer** [comment]
I think the `latest` documentation is referring to the requirements for the `0.10.0-rc` release that's upcoming and not the `0.9.15` release.

**Comment by howdoicomputer** [comment]
Also, this is more of a general comment but the `0.9.15` PyPi packages for graphite web and carbon are somewhat wonky in general. They were uploaded in 2015 - two years ago - and they have some breaking bugs.

I ran into this problem https://github.com/graphite-project/carbon/pull/486 for example

**Comment by tas50** [comment]
I reverted the django update commit with 6177287966e6397ac2a893ea05ca69d40e673e3a. Care to give that a try?

**Comment by howdoicomputer** [comment]
Seems to work! (Thanks for the commit)

**Comment by damacus** [comment]
@howdoicomputer thanks for letting us know about this issue.
