### ISSUE TITLE
Graphite cookbook failing due to runit::default

### ISSUE THREAD

**Issue by ff-pjha** [sous-chefs/graphite#290]
Cookbook version

[1.0.4]

Chef-client version

[ 12.5.1]

Platform Details

[Amazon Linux]

Scenario:

[Basically I am installing graphite cookbook, it is dependent on runit cookbook, and its failing]

Steps to Reproduce:

[Run runit::default]

Expected Result:

[runit installed]

Actual Result:

[runit not installed]

===============================================================================
Recipe: runit::default
* service[runit] action nothing (skipped due to action :nothing)
* execute[start-runsvdir] action nothing (skipped due to action :nothing)
* packagecloud_repo[imeyer/runit] action add
* yum_package[pygpgme] action install
- install version 0.3-9.12.amzn1 of package python26-pygpgme
* log[pygpgme_warning] action write (skipped due to not_if)
* ruby_block[disable repo_gpgcheck if no pygpgme] action run (skipped due to not_if)
* template[/etc/yum.repos.d/imeyer_runit.repo] action create
- create new file /etc/yum.repos.d/imeyer_runit.repo
- update content in file /etc/yum.repos.d/imeyer_runit.repo from none to c89480
--- /etc/yum.repos.d/imeyer_runit.repo	2017-11-15 09:52:10.331997906 +0000
+++ /etc/yum.repos.d/.imeyer_runit.repo20171115-2683-jighiv	2017-11-15 09:52:10.331997906 +0000
@@ -1 +1,11 @@
+[imeyer_runit]
+name=imeyer_runit
+baseurl=https://packagecloud.io/imeyer/runit/el/6/$basearch
+repo_gpgcheck=1
+gpgcheck=0
+enabled=1
+gpgkey=https://packagecloud.io/imeyer/runit/gpgkey
+sslverify=1
+sslcacert=/etc/pki/tls/certs/ca-bundle.crt
+metadata_expire=300
- change mode from '' to '0644'
* execute[yum-makecache-imeyer_runit] action run

         ================================================================================
         Error executing action `run` on resource 'execute[yum-makecache-imeyer_runit]'
         =============================================================================== Mixlib::ShellOut::ShellCommandFailed
         ------------------------------------
         Expected process to exit with [0], but received '1'
         ---- Begin output of yum -q makecache -y --disablerepo=* --enablerepo=imeyer_runit ----
         STDOUT: 
         STDERR: Existing lock /var/run/yum.pid: another copy is running as pid 14602.
         Another app is currently holding the yum lock; waiting for it to exit...
    The other application is: yum
      Memory :  90 M RSS (300 MB VSZ)
      Started: Wed Nov 15 09:52:07 2017 - 00:04 ago
      State  : Running, pid: 14602
         Another app is currently holding the yum lock; waiting for it to exit...
    The other application is: yum
      Memory : 182 M RSS (392 MB VSZ)
      Started: Wed Nov 15 09:52:07 2017 - 00:06 ago
      State  : Running, pid: 14602
         Importing GPG key 0xD59097AB:
   Userid     : "packagecloud ops (production key) <ops@packagecloud.io>"
   Fingerprint: 418a 7f2f b0e1 e6e7 eabf 6fe8 c2e7 3424 d590 97ab
   From       : https://packagecloud.io/imeyer/runit/gpgkey
         https://packagecloud.io/imeyer/runit/el/6/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for imeyer_runit
         Trying other mirror.

**Comment by ff-pjha** [comment]
Sorry for error indentation and readability. Basically the repo (imeyer_runit.repo) is not getting created inside yum.repos.d. Because of this the installation will not happen and the script of runit will not be created inside init.d.
Please provide a solution for this.

**Comment by ff-pjha** [comment]
Confirmed from runit cookbook issues, in the latest version of runit the issue has been resolved. But in the graphite cookbook the version of runit is not updated. In metadata its ">=1.2", but during execution its picking 1.8 version of runit. And the current release version of runit is 3.0.6. There is no attribute to override the package version of runit.
Please update it.

**Comment by tas50** [comment]
In general we're moving away from Runit in this cookbook, but you can create a wrapper cookbook you can specify the pin version of that cookbook if you want to ensure you pull in the latest version.

**Comment by ff-pjha** [comment]
One thing I have a small question, in the metadata the cookbook version specified for runit is ">=1.2" .
But whenever I converge it doesn't take the latest version of runit (3.0.6). It takes 1.0.8. 
Now you are saying to use a wrapper cookbook. So let me explain my architecture, I have my own cookbook in which I have made graphite as dependent inside metadata.rb and included the recipes. Now Graphite cookbook is dependent on runit, so how to override or disable it. I cannot specify the version of runit inside my metadata.rb, it is giving conflicts.
