### ISSUE TITLE
Contributors wanted!

### ISSUE THREAD

**Issue by damacus** [sous-chefs/graphite#295]
We need more contributors for this cookbook, if you would like to help maintain this cookbook please drop your name here!

**Comment by abilun** [comment]
I able to make some improvements

**Comment by damacus** [comment]
Excellent! 
If you haven't already, add yourself to the org and maintainers in this repo. 
https://github.com/sous-chefs/terraform-github-org

**Comment by abilun** [comment]
Here I am: [MR] (https://github.com/sous-chefs/terraform-github-org/pull/92).
But I don't quite understand why do I need to add myself to the list of contributors of mongodb cookbook, if I get you right.
