### ISSUE TITLE
No candidate version available for logstash

### ISSUE THREAD

**Issue by chakreshkolluru** [sous-chefs/graphite#312]
* No candidate version available for logstash
    ================================================================================
    Error executing action `install` on resource 'apt_package[logstash]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for logstash
    
    Resource Declaration:
    ---------------------
    cache/cache/cookbooks/logstash/recipes/default.rb
    
      6:  package "logstash" do
      7:  	action :install
      8:  end
      9: 
    
    Compiled Resource:
    ------------------
   cache/cache/cookbooks/logstash/recipes/default.rb:6:in `from_file'
    
    apt_package("logstash") do
      package_name "logstash"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "logstash"
      recipe_name "default"
end

How to solve this error

**Comment by ramereth** [comment]
This doesn't seem to be related to this cookbook.
