### ISSUE TITLE
ERROR: undefined method `python' for #<Chef::Node::Attribute:0x0000000001dc24a8

### ISSUE THREAD

**Issue by MarcusRosafield** [sous-chefs/graphite#319]
I'm running the test default.rb template in order to setup graphite but it is returning the error below, I've tried different versions of chef 13+. Please do you have any advice on this?

graphite: [2019-08-11T13:47:24+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> graphite: [2019-08-11T13:47:24+00:00] ERROR: undefined method `python' for #<Chef::Node::Attribute:0x0000000001dc24a8>
==> graphite: [2019-08-11T13:47:24+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by ramereth** [comment]
This is likely due to poise and should be resolved once #349 is completed. Closing as a duplicate to #349.
