### ISSUE TITLE
Release new version of 'graphite' cookbook to Chef Market

### ISSUE THREAD

**Issue by trynity** [sous-chefs/graphite#321]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

It's been a few years since the last release, and currently the version of the cookbook that is available on the Chef Market is not compatible with Chef 13+, and this has been fixed in git: https://github.com/sous-chefs/graphite/issues/274

## :pancakes: Cookbook version

1.0.4

**Comment by JohnRoesler** [comment]
Done - version 1.1.0 has been released
